// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      /* throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); */
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhmtuYu2pchlrfQ5qoobjZkzDYhpgRuc',
    appId: '1:485884426537:web:15668de371f80564905f38',
    messagingSenderId: '485884426537',
    projectId: 'gaya-food-delivery',
    authDomain: 'gaya-food-delivery.firebaseapp.com',
    storageBucket: 'gaya-food-delivery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-LRB3m7z-_tpMx6_d05P_uPmCnzW2x00',
    appId: '1:485884426537:android:4db4579f9cf46bb4905f38',
    messagingSenderId: '485884426537',
    projectId: 'gaya-food-delivery',
    storageBucket: 'gaya-food-delivery.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRhmtuYu2pchlrfQ5qoobjZkzDYhpgRuc',
    appId: '1:485884426537:web:0515e664bb512156905f38',
    messagingSenderId: '485884426537',
    projectId: 'gaya-food-delivery',
    authDomain: 'gaya-food-delivery.firebaseapp.com',
    storageBucket: 'gaya-food-delivery.appspot.com',
  );

}